/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    GameCanvas: typeof import('./src/components/Runner/GameCanvas.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LoginComponent: typeof import('./src/components/loginComponent.vue')['default']
    RouterView: typeof import('vue-router')['RouterView']
    TestGame: typeof import('./src/components/testGame.vue')['default']
    UserProfile: typeof import('./src/components/UserProfile.vue')['default']
  }
}
