/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/profile': RouteRecordInfo<'/profile', '/profile', Record<never, never>, Record<never, never>>,
    '/Runner': RouteRecordInfo<'/Runner', '/Runner', Record<never, never>, Record<never, never>>,
    '/sign_up': RouteRecordInfo<'/sign_up', '/sign_up', Record<never, never>, Record<never, never>>,
    '/stake_comp/Countdown': RouteRecordInfo<'/stake_comp/Countdown', '/stake_comp/Countdown', Record<never, never>, Record<never, never>>,
    '/stake_comp/GetBets': RouteRecordInfo<'/stake_comp/GetBets', '/stake_comp/GetBets', Record<never, never>, Record<never, never>>,
    '/staking': RouteRecordInfo<'/staking', '/staking', Record<never, never>, Record<never, never>>,
    '/wheel': RouteRecordInfo<'/wheel', '/wheel', Record<never, never>, Record<never, never>>,
  }
}
